version: '3.1'

services:
  postgres-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
    ports:
      - "5432:5432"
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.0.10"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
